### ISSUE TITLE
Missing Google+ user icon.

### ISSUE THREAD

**Issue by pnemonic78** [gorbin/ASNETutorial#3]
ASNETutorial\app\src\main\java\com\github\gorbin\asnetutorial\FriendsListAdapter.java
Error:(94, 35) error: cannot find symbol variable g_plus_user

ASNETutorial\app\src\main\java\com\github\gorbin\asnetutorial\ProfileFragment.java
Error:(188, 35) error: cannot find symbol variable g_plus_user

**Comment by b-e-e** [comment]
it doesn't solved yet
