### ISSUE TITLE
R.drawable.g_plus_user not found

### ISSUE THREAD

**Issue by najor** [gorbin/ASNETutorial#6]

**Comment by diprish** [comment]
I am facing the same issue. Can someone help?

**Comment by najor** [comment]
I had to add the image myself to the res folder.
Hope this helps you.

**Comment by anvesh523** [comment]
OfCourse @najor  .... We have to add our own image for that
r
already 3 images r there, U can use those too....

**Comment by najor** [comment]
Thanks.
